package exception_Error;

public class Erro3 {

	public static void main(String[] args) {
//		Example-1
		
//try {
//	int a[]=new int[5];
//	a[5]=50/0;
//	System.out.println(a[5]);
//}
//catch(ArithmeticException e1) {
//	System.out.println(e1);
//}
//catch(ArrayIndexOutOfBoundsException e2) {
//	System.out.println(e2);
//}
//catch(Exception e) {
//	System.out.println(e);
//}
//System.out.println("out of try catch block.");
		
//		Example-2
//		try {
//			String s=null;
//			System.out.println(s.length());
//		}
//		catch(ArithmeticException e1) {
//			System.out.println("Arithmatic exception occurs");
//		}
//		catch(ArrayIndexOutOfBoundsException e2) {
//			System.out.println("Arrray index out of bounds exception occurs");
//		}
//		catch(Exception e) {
//			System.out.println("Parent exception occurs");
//		}
//		System.out.println("out of try catch block.");
		
//		Example-3
//		Note-if we do not follow the order of Exception class, complile time error comes.
		
//		try {
//			String s[]= {"rohit","sam","alex"};
//			System.out.println(s[78]);
//		}
//		catch(Exception e) {
//			System.out.println("Parent exception occurs");
//		}
//		catch(ArrayIndexOutOfBoundsException e2) {
//			System.out.println("Arrray index out of bounds exception occurs");
//		}
//		showing compile time error.
		
		
	}

}
